import { NewProblem } from '../types';

export const DESIGN_QUESTIONS: NewProblem[] = [
  { title: 'LRU Cache', topic: 'Design', difficulty: 'Medium', leetcode_url: 'https://leetcode.com/problems/lru-cache/', list_name: 'Design Questions' },
  { title: 'LFU Cache', topic: 'Design', difficulty: 'Hard', leetcode_url: 'https://leetcode.com/problems/lfu-cache/', list_name: 'Design Questions' },
  { title: 'Design Browser History', topic: 'Design', difficulty: 'Medium', leetcode_url: 'https://leetcode.com/problems/design-browser-history/', list_name: 'Design Questions' },
  { title: 'Design File System', topic: 'Design', difficulty: 'Medium', leetcode_url: 'https://leetcode.com/problems/design-file-system/', list_name: 'Design Questions' },
  { title: 'Design HashMap', topic: 'Design', difficulty: 'Easy', leetcode_url: 'https://leetcode.com/problems/design-hashmap/', list_name: 'Design Questions' },
  { title: 'Design Twitter', topic: 'Design', difficulty: 'Medium', leetcode_url: 'https://leetcode.com/problems/design-twitter/', list_name: 'Design Questions' },
  { title: 'Design Excel Sum Formula', topic: 'Design', difficulty: 'Hard', leetcode_url: 'https://leetcode.com/problems/design-excel-sum-formula/', list_name: 'Design Questions' },
  { title: 'Design In-Memory File System', topic: 'Design', difficulty: 'Hard', leetcode_url: 'https://leetcode.com/problems/design-in-memory-file-system/', list_name: 'Design Questions' },
  { title: 'Design Search Autocomplete System', topic: 'Design', difficulty: 'Hard', leetcode_url: 'https://leetcode.com/problems/design-search-autocomplete-system/', list_name: 'Design Questions' },
  { title: 'Design Log Storage System', topic: 'Design', difficulty: 'Medium', leetcode_url: 'https://leetcode.com/problems/design-log-storage-system/', list_name: 'Design Questions' },
  { title: 'Design Hit Counter', topic: 'Design', difficulty: 'Medium', leetcode_url: 'https://leetcode.com/problems/design-hit-counter/', list_name: 'Design Questions' },
  { title: 'Design Underground System', topic: 'Design', difficulty: 'Medium', leetcode_url: 'https://leetcode.com/problems/design-underground-system/', list_name: 'Design Questions' },
  { title: 'Design Circular Queue', topic: 'Design', difficulty: 'Medium', leetcode_url: 'https://leetcode.com/problems/design-circular-queue/', list_name: 'Design Questions' },
  { title: 'Design Circular Deque', topic: 'Design', difficulty: 'Medium', leetcode_url: 'https://leetcode.com/problems/design-circular-deque/', list_name: 'Design Questions' },
  { title: 'Design Bounded Blocking Queue', topic: 'Design', difficulty: 'Medium', leetcode_url: 'https://leetcode.com/problems/design-bounded-blocking-queue/', list_name: 'Design Questions' },
  { title: 'Design Snake Game', topic: 'Design', difficulty: 'Medium', leetcode_url: 'https://leetcode.com/problems/design-snake-game/', list_name: 'Design Questions' },
  { title: 'Design Tic-Tac-Toe', topic: 'Design', difficulty: 'Medium', leetcode_url: 'https://leetcode.com/problems/design-tic-tac-toe/', list_name: 'Design Questions' },
  { title: 'Implement Stack using Queues', topic: 'Design', difficulty: 'Easy', leetcode_url: 'https://leetcode.com/problems/implement-stack-using-queues/', list_name: 'Design Questions' },
  { title: 'Implement Queue using Stacks', topic: 'Design', difficulty: 'Easy', leetcode_url: 'https://leetcode.com/problems/implement-queue-using-stacks/', list_name: 'Design Questions' },
  { title: 'Implement Trie Prefix Tree', topic: 'Design', difficulty: 'Medium', leetcode_url: 'https://leetcode.com/problems/implement-trie-prefix-tree/', list_name: 'Design Questions' },
  { title: 'Design Add and Search Words Data Structure', topic: 'Design', difficulty: 'Medium', leetcode_url: 'https://leetcode.com/problems/design-add-and-search-words-data-structure/', list_name: 'Design Questions' },
  { title: 'Find Median from Data Stream', topic: 'Design', difficulty: 'Hard', leetcode_url: 'https://leetcode.com/problems/find-median-from-data-stream/', list_name: 'Design Questions' },
  { title: 'Insert Delete GetRandom O(1)', topic: 'Design', difficulty: 'Medium', leetcode_url: 'https://leetcode.com/problems/insert-delete-getrandom-o1/', list_name: 'Design Questions' },
  { title: 'All O`one Data Structure', topic: 'Design', difficulty: 'Hard', leetcode_url: 'https://leetcode.com/problems/all-oone-data-structure/', list_name: 'Design Questions' },
  { title: 'Maximum Frequency Stack', topic: 'Design', difficulty: 'Hard', leetcode_url: 'https://leetcode.com/problems/maximum-frequency-stack/', list_name: 'Design Questions' },
];
